#spring.application.name=micro-lms-api-gateway-sb
spring:
  application:
    name: micro-lms-api-gateway-sb
  cloud:
    gateway:
      routes:
#        - id: user_route
#          uri: http://localhost:5000
#          predicates:
#            - Path=/users/**
        - id: media_route
          uri: http://localhost:5001
          predicates:
            - Path=/media/**
server:
  port: 8081